### PR TITLE
Fix Testing section in README

### PR DESCRIPTION
**Pull request by bwaidelich**
The Testing section referred to a non-existing composer script `test`

### CODE REVIEW

**Comment by bwaidelich** [comment]
Let me know if you want me to add the missing composer script instead and I'll push a follow-up

**Comment by Crell** [comment]
We've got a phpstan script, so may as well make one for tests.  Although I rarely use them, as for reasons I've never figured out running a composer script when xdebug is enabled just hangs, at least on my Docker images.  I've yet to figure out why... 😢 

In any case, yes, let's add the script instead to match the readme.

**Comment by bwaidelich** [comment]
> We've got a phpstan script, so may as well make one for tests

Done.
I did not adjust `Makefile` and `quality-assurance.yaml` to use the script since they weren't using the phpstan script either

> running a composer script when xdebug is enabled just hangs

uh? I've never experienced that

**Comment by Crell** [comment]
> uh? I've never experienced that

Yeah, I can't explain it either.

Thanks!

**Pull request merged**
